// v2: 使用 Array.join 避免 template literal 衝突
const fs = require('fs')
const path = 'c:/Users/humphery/coding/recoder/frontend/electron/main.js'
let src = fs.readFileSync(path, 'utf8')

const anchor = '// ── 聲紋說話者標註 ──'

const lines = []
lines.push('')
lines.push('// v1.23.0: Speaker Profile Database CRUD')
lines.push("ipcMain.handle('voiceprint:profileList', async () => {")
lines.push('  try {')
lines.push('    const profiles = speakerProfile.listProfiles()')
lines.push('    const stats = speakerProfile.getStats()')
lines.push('    return { success: true, profiles, stats }')
lines.push('  } catch (e) { return { success: false, error: e.message } }')
lines.push('})')
lines.push('')
lines.push("ipcMain.handle('voiceprint:profileSave', async (event, profile) => {")
lines.push('  try { return speakerProfile.saveProfile(profile) }')
lines.push('  catch (e) { return { success: false, error: e.message } }')
lines.push('})')
lines.push('')
lines.push("ipcMain.handle('voiceprint:profileRename', async (event, payload) => {")
lines.push('  try { return speakerProfile.renameProfile(payload.id, payload.newName) }')
lines.push('  catch (e) { return { success: false, error: e.message } }')
lines.push('})')
lines.push('')
lines.push("ipcMain.handle('voiceprint:profileDelete', async (event, payload) => {")
lines.push('  try { return speakerProfile.deleteProfile(payload.id) }')
lines.push('  catch (e) { return { success: false, error: e.message } }')
lines.push('})')
lines.push('')
lines.push("ipcMain.handle('voiceprint:profileStats', async () => {")
lines.push('  try { return { success: true, ...speakerProfile.getStats() } }')
lines.push('  catch (e) { return { success: false, error: e.message } }')
lines.push('})')
lines.push('')
lines.push('// v1.23.0: 從 seeds 建立 profile')
lines.push("ipcMain.handle('voiceprint:profileBuildFromSeeds', async (event, payload) => {")
lines.push('  const { audioPath, segments, seeds, modelKey } = payload')
lines.push('  appLog("INFO", "voiceprint", `buildProfile: ${audioPath} (${seeds.length} seeds, modelKey=${modelKey})`)')
lines.push('  try {')
lines.push('    const profiles = await voiceprint.buildProfile(audioPath, segments, seeds, modelKey)')
lines.push('    const savedIds = []')
lines.push('    for (const p of profiles) {')
lines.push('      const r = speakerProfile.saveProfile(p)')
lines.push('      if (r.success) savedIds.push(r.id)')
lines.push('    }')
lines.push('    appLog("INFO", "voiceprint", `建立 ${savedIds.length}/${profiles.length} 個 profile`)')
lines.push('    return { success: true, profiles, savedIds, count: savedIds.length }')
lines.push('  } catch (e) {')
lines.push('    appLog("ERROR", "voiceprint", `buildProfile 失敗: ${e.message}`)')
lines.push('    return { success: false, error: e.message }')
lines.push('  }')
lines.push('})')
lines.push('')
lines.push('// v1.23.0: 從獨立短音檔建立 profile')
lines.push("ipcMain.handle('voiceprint:profileBuildFromAudioFile', async (event, payload) => {")
lines.push('  const { audioPath, name, modelKey } = payload')
lines.push('  appLog("INFO", "voiceprint", `buildProfileFromAudioFile: ${audioPath} name=${name} modelKey=${modelKey}`)')
lines.push('  try {')
lines.push('    const p = await voiceprint.buildProfileFromAudioFile(audioPath, name, modelKey)')
lines.push('    const r = speakerProfile.saveProfile(p)')
lines.push('    if (r.success) return { success: true, profile: { ...p, id: r.id }, id: r.id }')
lines.push('    return r')
lines.push('  } catch (e) {')
lines.push('    appLog("ERROR", "voiceprint", `buildProfileFromAudioFile 失敗: ${e.message}`)')
lines.push('    return { success: false, error: e.message }')
lines.push('  }')
lines.push('})')
lines.push('')
lines.push('// v1.23.0: 開啟檔案選擇器選擇音檔')
lines.push("ipcMain.handle('voiceprint:openAudioDialog', async () => {")
lines.push('  try {')
lines.push('    const r = await dialog.showOpenDialog(mainWindow, {')
lines.push("      title: '選擇音檔',")
lines.push("      properties: ['openFile'],")
lines.push("      filters: [")
lines.push("        { name: '音訊檔案', extensions: ['wav', 'mp3', 'opus', 'ogg', 'flac', 'm4a', 'webm'] },")
lines.push("        { name: '所有檔案', extensions: ['*'] }")
lines.push('      ]')
lines.push('    })')
lines.push('    if (r.canceled || r.filePaths.length === 0) return { success: false, cancelled: true }')
lines.push('    return { success: true, path: r.filePaths[0] }')
lines.push('  } catch (e) { return { success: false, error: e.message } }')
lines.push('})')
lines.push('')
lines.push('// v1.23.0: 有監督式 speaker identification')
lines.push("ipcMain.handle('voiceprint:identifySpeakers', async (event, payload) => {")
lines.push('  const { audioPath, segments, modelKey, threshold } = payload')
lines.push('  appLog("INFO", "voiceprint", `identifySpeakers: ${audioPath} (${segments.length} 句, modelKey=${modelKey})`)')
lines.push('  try {')
lines.push('    const profiles = speakerProfile.getProfilesByModel(modelKey || "camplus")')
lines.push('    if (profiles.length === 0) {')
lines.push('      return { success: false, error: `沒有 modelKey=${modelKey} 的 profile，請先建立 speaker profile`, profiles: [] }')
lines.push('    }')
lines.push('    const opts = {}')
lines.push('    if (typeof threshold === "number") opts.threshold = threshold')
lines.push('    const r = await voiceprint.identifySpeakers(audioPath, segments, profiles, opts)')
lines.push('    appLog("INFO", "voiceprint", `辨識完成: ${r.matches.length} 個 segment 匹配到 profiles`)')
lines.push('    return { success: true, segments: r.segments, matches: r.matches, modelKey: r.modelKey }')
lines.push('  } catch (e) {')
lines.push('    appLog("ERROR", "voiceprint", `identifySpeakers 失敗: ${e.message}`)')
lines.push('    return { success: false, error: e.message }')
lines.push('  }')
lines.push('})')
lines.push('')
lines.push('// v1.23.0: 批次對所有歷史錄音套用所有 profiles')
lines.push("ipcMain.handle('voiceprint:backfillAll', async (event, payload = {}) => {")
lines.push('  const { modelKey, threshold } = payload')
lines.push('  appLog("INFO", "voiceprint", `backfillAll: 對所有歷史錄音套用 profiles (modelKey=${modelKey})`)')
lines.push('  try {')
lines.push('    const profiles = speakerProfile.getProfilesByModel(modelKey || "camplus")')
lines.push('    if (profiles.length === 0) return { success: false, error: "無 profile", processed: 0 }')
lines.push('    const dir = recoDataPath()')
lines.push('    if (!fs.existsSync(dir)) return { success: true, processed: 0 }')
lines.push('    const files = scanJsonFiles(dir)')
lines.push('    const metaFiles = files.filter(f => f.endsWith(".json"))')
lines.push('    let processed = 0, matched = 0')
lines.push('    const startTime = Date.now()')
lines.push('    for (let i = 0; i < metaFiles.length; i++) {')
lines.push('      const metaPath = metaFiles[i]')
lines.push('      try {')
lines.push('        const meta = JSON.parse(fs.readFileSync(metaPath, "utf-8"))')
lines.push('        if (!meta.segments || meta.segments.length === 0 || !meta.audioPath) continue')
lines.push('        if (!fs.existsSync(meta.audioPath)) continue')
lines.push('        if (mainWindow) mainWindow.webContents.send("voiceprint:backfill-progress", { current: i + 1, total: metaFiles.length, recordingId: meta.id })')
lines.push('        const opts = {}')
lines.push('        if (typeof threshold === "number") opts.threshold = threshold')
lines.push('        const r = await voiceprint.identifySpeakers(meta.audioPath, meta.segments, profiles, opts)')
lines.push('        for (let j = 0; j < r.segments.length && j < meta.segments.length; j++) {')
lines.push('          meta.segments[j].speaker = r.segments[j].speaker || meta.segments[j].speaker || ""')
lines.push('          if (r.segments[j].score !== undefined) meta.segments[j].score = r.segments[j].score')
lines.push('        }')
lines.push('        fs.writeFileSync(metaPath, JSON.stringify(meta, null, 2), "utf-8")')
lines.push('        processed++; matched += r.matches.length')
lines.push('      } catch (e) {')
lines.push('        appLog("WARN", "voiceprint", `backfill 跳過 ${metaPath}: ${e.message}`)')
lines.push('      }')
lines.push('    }')
lines.push('    const elapsed = ((Date.now() - startTime) / 1000).toFixed(1)')
lines.push('    appLog("INFO", "voiceprint", `backfillAll 完成: ${processed} 個錄音, ${matched} 個匹配, ${elapsed}s`)')
lines.push('    return { success: true, processed, matched, elapsed }')
lines.push('  } catch (e) {')
lines.push('    appLog("ERROR", "voiceprint", `backfillAll 失敗: ${e.message}`)')
lines.push('    return { success: false, error: e.message }')
lines.push('  }')
lines.push('})')
lines.push('')
lines.push('// v1.23.0: 跨錄音 speaker-aware 搜尋')
lines.push("ipcMain.handle('reco:searchBySpeaker', async (event, payload) => {")
lines.push('  const { speakerName, keyword } = payload')
lines.push('  appLog("INFO", "reco", `searchBySpeaker: speakerName="${speakerName}" keyword="${keyword || ""}"`)')
lines.push('  try {')
lines.push('    const dir = recoDataPath()')
lines.push('    if (!fs.existsSync(dir)) return { success: true, results: [] }')
lines.push('    const files = scanJsonFiles(dir)')
lines.push('    const results = []')
lines.push('    for (const metaPath of files) {')
lines.push('      try {')
lines.push('        const data = JSON.parse(fs.readFileSync(metaPath, "utf-8"))')
lines.push('        if (!Array.isArray(data.segments)) continue')
lines.push('        for (let i = 0; i < data.segments.length; i++) {')
lines.push('          const seg = data.segments[i]')
lines.push('          if (seg.speaker !== speakerName) continue')
lines.push('          if (keyword && !seg.text.toLowerCase().includes(keyword.toLowerCase())) continue')
lines.push('          results.push({')
lines.push('            recordingId: data.id, filename: data.filename, recordedAt: data.recordedAt,')
lines.push('            start: seg.start, end: seg.end, text: seg.text, speaker: seg.speaker,')
lines.push('            score: seg.score || 0, source: "original",')
lines.push('          })')
lines.push('        }')
lines.push('      } catch (e) {}')
lines.push('    }')
lines.push('    appLog("INFO", "reco", `searchBySpeaker 完成: ${results.length} 個結果`)')
lines.push('    return { success: true, results, count: results.length }')
lines.push('  } catch (e) {')
lines.push('    appLog("ERROR", "reco", `searchBySpeaker 失敗: ${e.message}`)')
lines.push('    return { success: false, error: e.message }')
lines.push('  }')
lines.push('})')
lines.push('')
lines.push('// v1.23.0: 列出所有 speaker 名稱')
lines.push("ipcMain.handle('voiceprint:listAllSpeakerNames', async () => {")
lines.push('  try {')
lines.push('    const nameSet = new Set()')
lines.push('    for (const p of speakerProfile.listProfiles()) nameSet.add(p.name)')
lines.push('    const dir = recoDataPath()')
lines.push('    if (fs.existsSync(dir)) {')
lines.push('      for (const metaPath of scanJsonFiles(dir)) {')
lines.push('        try {')
lines.push('          const data = JSON.parse(fs.readFileSync(metaPath, "utf-8"))')
lines.push('          if (Array.isArray(data.segments)) {')
lines.push('            for (const seg of data.segments) {')
lines.push('              if (seg.speaker && seg.speaker.startsWith("Speaker_") === false) {')
lines.push('                nameSet.add(seg.speaker)')
lines.push('              }')
lines.push('            }')
lines.push('          }')
lines.push('        } catch (e) {}')
lines.push('      }')
lines.push('    }')
lines.push('    return { success: true, names: Array.from(nameSet).sort() }')
lines.push('  } catch (e) { return { success: false, error: e.message } }')
lines.push('})')

const ipcBlock = lines.join('\n')

if (src.includes("voiceprint:profileList'")) {
  console.log('SKIP: v1.23.0 IPC handlers already present')
} else {
  src = src.replace(anchor, ipcBlock + '\n\n' + anchor)
  fs.writeFileSync(path, src, 'utf8')
  console.log('OK: appended v1.23.0 IPC handlers, total lines:', lines.length)
}